# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='prof',
            field=models.CharField(choices=[('CLEANER', 'cleaning dep'), ('KITCHEN', 'people from kitchen dep'), ('PILOT', 'spaceship pilot'), ('DOCTOR', 'person treating people')], default='UNEMPLOYED', max_length=20),
        ),
    ]
