# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0002_auto_20180318_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MY BEST MONTH')], default=('JAN', 'JANUARY'), max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='prof',
            field=models.CharField(choices=[('CLEANER', 'cleaning dep'), ('KITCHEN', 'people from kitchen dep'), ('PILOT', 'spaceship pilot'), ('DOCTOR', 'person treating people')], default=('CLEANER', 'cleaning dep'), max_length=20),
        ),
    ]
